# Generated by Django 4.1.6 on 2023-02-14 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('rollno', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('pwd', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('sem', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=11)),
                ('pphone', models.CharField(max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('pwd', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=11)),
                ('sem', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='student_requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=100, unique=True)),
                ('reason', models.CharField(max_length=300)),
                ('guardian_phone', models.CharField(max_length=11)),
                ('relation', models.CharField(max_length=100)),
                ('guardian_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('cc', models.CharField(blank=True, max_length=100, null=True)),
                ('hod', models.CharField(blank=True, max_length=100, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.students')),
            ],
        ),
    ]
