# Generated by Django 4.1.6 on 2023-02-14 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_requests',
            name='cc',
        ),
        migrations.RemoveField(
            model_name='student_requests',
            name='hod',
        ),
    ]
