# Generated by Django 4.1.6 on 2023-02-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0002_remove_student_requests_cc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_requests',
            name='cc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student_requests',
            name='hod',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
